### ISSUE TITLE
Chapter headings in main body

### ISSUE THREAD

**Issue by shigginson** [dankelley/dal-oce-thesis#16]
FGS tell me that multi-line chapter headings in the main body of the thesis must be single spaced (Also in the TOC, but this has been covered elsewhere)

I added "\linespread{1}" to line 257 on my copy of ocethesis to achieve this.

This solution is imperfect - the signature page and abstract also change to single spaced lines. I added a change to revert these other sections back to their regular spacing i.e."\linespread{1.37}\normalsize" added before line 710

**Comment by dankelley** [comment]
Closing, on the recommendation in the previous comment.
