### ISSUE TITLE
signature page can break in two

### ISSUE THREAD

**Issue by pmattern-zz** [dankelley/dal-oce-thesis#21]
Under certain circumstances the signature page (page ii) can break, making the thesis not confirm to FGS standards and making FGS complain.

To recreate the error: remove the \fourthreader in \phd mode in mythesis.tex. (In my thesis, there is also no third reader but a second supervisor and the error still occurs.)

The effect: the signature page breaks in two pages and the "Departmental Representative" gets two signature lines.

**Comment by dankelley** [comment]
I'm closing this because it's so old. Also, signature pages no longer exist.
