### ISSUE TITLE
2 more issues (co-supervisors and horizontal lines)

### ISSUE THREAD

**Issue by pmattern-zz** [dankelley/dal-oce-thesis#22]
I don't think that these 2 issues deserve their own topic, so I am lumping them together here. After receiving NO suggestions for corrections on my last FGS format check, I submitted my thesis online... to get it rejected the next day. The following explanation was given:

```
1) On your signature page, you need to change Supervisors to Co-Supervisors

2) I suggest removing the horizontal lines surrounding your main chapter headings.
```

The first point seems valid and would be a good addition for the "signature page can break in two" bug fix. I'll try to fix it the hardcoding way for my thesis now.

The second point is a suggestion and I will not follow it unless I find the source of the "problem" very fast. I just wanted to make it known that FGS is taking an issue with these lines.

**Comment by dankelley** [comment]
I'm closing this because it's so old, and also signature pages no longer exist.
