### ISSUE TITLE
FGS wants 1.5 to 2x spacing between subsections in TOC

### ISSUE THREAD

**Issue by JaredButler** [dankelley/dal-oce-thesis#24]
Just got my first format check from FGS and they want 1.5 (or 2x) linespacing between subsections in the TOC. The version of ocethesis I'm using does single spaced subsections. Is there a quick fix for this? I know of a thesis submitted a few months ago where this wasn't an issue - must be a new rule.

**Comment by dankelley** [comment]
I'm closing this issue because it's two years old and I think FGS is reporting a similar problem ... but that should be a new issue, so I (and the new student) can track it.
