### ISSUE TITLE
wrong page number for Table of Contents

### ISSUE THREAD

**Issue by dankelley** [dankelley/dal-oce-thesis#26]
For example, in the ``mythesis`` test document, the ToC is coming out as page ``iv`` but it should be `iii`. That case has a dedication. A student has a similar problem with a thesis where there is no dedication, and there the ToC is coming out as page ``iii`` but it should be ``ii``.

Probable cause -- the counter that used to be incremented over the signature pages is probably still being incremented.

**Comment by GodinA** [comment]
Hi Dan, I just ran your new version on my dissertation and the pagination issues with ToC and no dedication page is fixed!  i.e., ToC now starts at `ii`. Thanks!

**Comment by dankelley** [comment]
Thanks. Accordingly, I am now closing the issue. Please open another one regarding line spacing, if that's something that they require. Dan.
