### ISSUE TITLE
TOC spacing

### ISSUE THREAD

**Issue by ecjoliver** [dankelley/dal-oce-thesis#5]
Table of contents.  If possible use 1.5-2 line-spacing between entries; double-lined headings/titles should be single-spaced .

**Comment by dankelley** [comment]
I'm going to close this now. I think a newer student is having problems, but of course I can always examine this closed issue to get hints, if needed. I see a merged code from @richardsc back in December of 2011 in the git log, so I'm guessing that whatever was learned in the present issue made its way into the style sheet. Basically, I want to address a new issue as a new issue, without going back 3 years in the code to check. So closing.
