### ISSUE TITLE
Co-supervisors

### ISSUE THREAD

**Issue by jrconrad** [dankelley/dal-oce-thesis#7]
I have two supervisors.  In the main document to be typeset, when I type \supervisor{} twice, it gives me "Supervisors:" on the signature page.  However, FGS requires that this say "Co-Supervisors."  I suspect that "Supervisor" and "Co-supervisor" as appears to be written in the .cls would be suitable, but this doesn't seem to work for me either.  I noted "superviser" somewhere in the .cls file, so maybe that's causing the problem.  I've band-aided the issue for myself, but maybe this could be looked into in the future.

**Comment by dankelley** [comment]
I'm closing this because signature pages no longer exist.
