### ISSUE TITLE
CAPS in chapter headings vs. TOC

### ISSUE THREAD

**Issue by jrconrad** [dankelley/dal-oce-thesis#8]
"In the TOC your chapter headings are in Title case, but on the actual pages (both preliminary pages and the start of each main chapter) they are in all-caps.  Make sure they match."

I noted that Dan could not change this in the README file, so I told FGS that I couldn't change this and that other thesis (theses?) have been submitted using this format.  Hopefully, they won't care, but I figure you might as well know that they still have an issue with this.

**Comment by dankelley** [comment]
I'm closing this because either it's been settled for 3 years or it will crop up again. Most likely FGS saw that the recommendation was silly, and dropped it.
